name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "threadpoolfix"
      BUILD_64x: "true"
      REALM: "sv"
      BUILD_WINDOWS: "false"
      BUILD_32x: "false"  